Notebook 1, Module 1, Data and Data Management, CAS Applied Data Science, 2024-08-21, A. Mühlemann, University of Bern. (based on the template by S. Haug)

Prerequisite for this notebook is some basic Python experience.

Please also look at the first batch of [the slides](https://drive.google.com/file/d/12cWTQG5_vcoaz-puhBgH9GrfKUADmLdo/view?usp=sharing) before doing this notebook. They offer an introduction to data.

ChatGPT is able to write most of the code needed for this notebook. Please use it if you like!

# 1. Data Management

Estimated study time is about 2 hours. According to your background and how much you want to learn, you may need more or less. You are supposed to google, read manuals and chat with others during working through this notebook in order to benefit fully.

**Learning outcomes - after completion you**
- Know about data sources, types and formats (see lecture slides via link above)
- Able to import and export data in Python
- Able to do simple things with dataframes in Python

**Documentation on Pandas DataFrame**
- Python: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

## Outline

     0. About data management
     1. Getting used to Jupyter notebooks / colab
     2. Importing and merging
     3. Indexing on a dataframe
     4. Sorting
     5. Filtering
     6. Exporting
     7. Missing and bad data
     8. Metadata
     9. Working on the filesystem

## 0. About data management

Handling or managing data involves many steps and technologies at many levels. Data may be colleccted by sensors. It can be a camera, a temperature sensor, a telescope, a microscope (with a camera), a microphone, a particle detector etc. Normally the data is then digitised, maybe preprocessed and written to some media in a certain format, e.g. as a comma separated value (csv) file to a hard disk. This part of the data management is normally taken care of by engineers.

Data may also be collected from all sorts of databases, so data already collected somehow. Time series of financial data, customers, passengers, facebook likes, twitter tweets etc. This is data which is normally already on a media with some interface for access, e.g. paper to be read by a camera, a file on youtube, a table on wikipedia etc. We will look at some ways to collect such data. Some programming and computer skills are needed to do so. It may be that this part of the data management is taken care of by specialised computer scientists, but it may also be expected from a data scientist to have these skills.

Analysing data with statisitical and machine learning tools, requires that the data is colleceted, cleaned and prepared for the tools. *This is very often a very large part of a data analytics project and a prerequisite*. It may involve removing bad data, filter out redundant and noisy data, unify the formats and types, transform the data etc.
Thus, a data scientist must be able to perform this part of the data management. This notebook shows the basic operations with Python pandas. With other tools the concepts and operations are very similar.

After the data analysis, after the extraction of information and the creation of knowledge, the data is often stored or archived for the future (if this seems cheaper than regenerating the data at a later point). In larger institutions this part of the data management may include educated librarians and others, not necessarily the data scientist.  

**In this notebook we only look at a few examples on how to do datamanagement with dataframes. Pandas are extremly powerful and we cannot show everything in a couple of hours. You will become more and more experienced when you work on your module projects. Probably whatever you want to do with your dataframe, there is a way to do it. If not, it probably doesn't make much sense what wou want to do.**

Any questions?

## 1. Getting used to Jupyter computational notebooks and Colab

With Jupyter you can write rich text notebooks with executable code via your browser. There are several so-called kernels or computational back ends, i.e Python, R, Julia, bash etc can be supported. The text is written as Markdown. Latex is also supported (good for math). You can export the notebook in various formats, e.g. html. Everything can be done via the various tabs, however, the key shortcuts make you faster.

*Useful key combinations*

- Shift Enter or Control Enter = Run cell
- Option/Alt Enter = Run cell and Insert new cell below

### Exercise 1 (10 min)
- Change and run this cell
- Add a new cell and execute some python statement in it
- Study the tabs in the menu of your jupyter (lab) notebook

In [ ]:
# Write some more Python code here
print("hello world!")

hello world!

## 2. Import a dataset into a Pandas DataFrame

Pandas is a Python Module for data analysis and manipulation and management. It has the data structure DataFrame which is quite powerful. Features

- DataFrame object for data management with integrated indexing.
- Tools for reading and writing data between in-memory data structures and different file formats.
- Data alignment and integrated handling of missing data.
- Reshaping and pivoting of data sets.
- Label-based slicing, fancy indexing, and subsetting of large data sets.
- Data structure column insertion and deletion.
- Group by engine allowing split-apply-combine operations on data sets.
- Data set merging and joining.
- Hierarchical axis indexing to work with high-dimensional data in a lower-dimensional data structure.
- Time series-functionality: Date range generation and frequency conversion, moving window statistics, moving window linear regressions, date shifting and lagging.

The module is highly optimized for performance, with critical code parts written in Cython or C. Documentation here: https://pandas.pydata.org/pandas-docs/stable/api.html

For input/output (I/O) there are methods for reading EXCEL, SQL databases, HTML tables, clipboard, SAS, STATA etc.

In this notebook we will work with a dataset that contains brain and body weight, life  span, gestation time,  sleep and danger indices of 62 mammals [(source)](https://lib.stat.cmu.edu/datasets/sleep).

To better illustrate some challenges faced when working with data, I split the data set into *sleep.csv* and *danger.csv* that can be downloaded from Github.

The data set *sleep.csv* contains:
* Species: species of animal
* BodyWt: body weight in kg
* BrainWt: brain weight in g
* NonDreaming: slow wave ("nondreaming") sleep (hrs/day)
* Dreaming: paradoxical ("dreaming") sleep (hrs/day)
* TotalSleep: total sleep (hrs/day)  (sum of slow wave and paradoxical sleep)
* LifeSpan: maximum life span (years)
* Gestation: gestation time (days)

The data set *danger.csv* contains:
* Species: species of animal
* Predation: predation index (1-5)\
1 = minimum (least likely to be preyed upon)\
5 = maximum (most likely to be preyed upon)
* Exposure: sleep exposure index (1-5)\
1 = least exposed (e.g. animal sleeps in a well-protected den)\
5 = most exposed
* Danger: overall danger index (1-5) based on the above two indices and other information
1 = least danger (from other animals)\
5 = most danger (from other animals)


### Exercise 2
- Upload both files to Colab
- Import the python module pandas with abbriveation pd
- Read both data sets into a pd dataframe
- Look at both dataframes and identify possible problems that could surface when trying to merge the dataframes

#### Hint

There are some ways to get help about modules and methods directly in Jupyter:

```
dataframe. #(hover over the object to see its methods)
```
or

```
dataframe?
```

And, what you will probably use the most, the online package information and examples by googling or ChatGPT.

In [5]:
# Upload the local data file to colab
from google.colab import files
uploaded = files.upload()

Saving danger.csv to danger.csv

In [6]:
# import the python module pandas with the abbreviation pd
import pandas as pd
# Read the data in the sleep.csv file into a dataframe
sleep = pd.read_csv('sleep.csv', sep=";")
# Read the data in the danger.csv file into a dataframe
danger = pd.read_csv('danger.csv', sep=";",  index_col=0)

In [7]:
# show sleep.csv
data = sleep.dropna()
data

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation
1,Africangiantpouchedrat,1.000,6.60,6.3,2.0,8.3,4.5,42.0
4,Asianelephant,2547.000,4603.00,2.1,1.8,3.9,69.0,624.0
5,Baboon,10.550,179.50,9.1,0.7,9.8,27.0,180.0
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0
8,Cat,3.300,25.60,10.9,3.6,14.5,28.0,63.0
9,Chimpanzee,52.160,440.00,8.3,1.4,9.7,50.0,230.0
10,Chinchilla,0.425,6.40,11.0,1.5,12.5,7.0,112.0
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0
14,EasternAmericanmole,0.075,1.20,6.3,2.1,8.4,3.5,42.0
15,Echidna,3.000,25.00,8.6,0.0,8.6,50.0,28.0
16,Europeanhedgehog,0.785,3.50,6.6,4.1,10.7,6.0,42.0
17,Galago,0.200,5.00,9.5,1.2,10.7,10.4,120.0
21,Goat,27.660,115.00,3.3,0.5,3.8,20.0,148.0
22,Goldenhamster,0.120,1.00,11.0,3.4,14.4,3.9,16.0
24,Grayseal,85.000,325.00,4.7,1.5,6.2,41.0,310.0
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0
27,Guineapig,1.040,5.50,7.4,0.8,8.2,7.6,68.0
28,Horse,521.000,655.00,2.1,0.8,2.9,46.0,336.0
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0
33,Man,62.000,1320.00,6.1,1.9,8.0,100.0,267.0
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0
38,NAmericanopossum,1.700,6.30,13.8,5.6,19.4,5.0,12.0
39,Nine-bandedarmadillo,3.500,10.80,14.3,3.1,17.4,6.5,120.0
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0
42,Patasmonkey,10.000,115.00,10.0,0.9,10.9,20.2,170.0
43,Phanlanger,1.620,11.40,11.9,1.8,13.7,13.0,17.0
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0
45,Rabbit,2.500,12.10,7.5,0.9,8.4,18.0,31.0
47,Rat,0.280,1.90,10.6,2.6,13.2,4.7,21.0
48,Redfox,4.235,50.40,7.4,2.4,9.8,9.8,52.0
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0
50,Rockhyrax(Heterob),0.750,12.30,5.7,0.9,6.6,7.0,225.0
51,Rockhyrax(Procaviahab),3.600,21.00,4.9,0.5,5.4,6.0,225.0
53,Sheep,55.500,175.00,3.2,0.6,3.8,20.0,151.0
56,Tenrec,0.900,2.60,11.0,2.3,13.3,4.5,60.0
57,Treehyrax,2.000,12.30,4.9,0.5,5.4,7.5,200.0
58,Treeshrew,0.104,2.50,13.2,2.6,15.8,2.3,46.0
59,Vervet,4.190,58.00,9.7,0.6,10.3,24.0,210.0
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0

The dataframe method shows 50 rows per default. We can change with

```
pd.set_option('display.max_rows', None)
```

In [8]:
# show danger.csv
danger

,Yellow-belliedmarmot,Wateropossum,Vervet,Treeshrew,Treehyrax,Tenrec,Starnosedmole,Slowloris,Sheep,Roedeer,...,Chimpanzee,Cat,Braziliantapir,Bigbrownbat,Baboon,Asianelephant,Arcticgroundsquirrel,ArcticFox,Africangiantpouchedrat,Africanelephant
Predation,3,2,4,3,3,2,3,2,5,5,...,1,1,4,1,4,3,5,1,3,3
Exposure,1,1,3,2,1,1,1,2,5,5,...,1,2,5,1,4,5,2,1,1,5
Danger,1,1,4,2,3,2,2,2,5,5,...,1,1,4,1,4,4,3,1,3,3

Some of the callenges are that in *sleep.csv* each row corresponds to a species, while for *danger.csv* it's the columns that correspond to a species. Moreover, in *sleep.csv* the species are sorted from A-Z, while for *danger.csv* they are sorted from Z-A.

### Exercise 3
Merge the two dataframes. We take *sleep.csv* as are base and want to add the information of *danger.csv* to the sleep dataframe. There are of course multiple solutions but try to make de modifications in Python and not with Excel.

In [14]:
# transpose danger.csv
danger_t = danger.transpose().reset_index()
danger_t.rename(columns={'index': 'Species'}, inplace=True)

# merge danger_t with sleep
dataframe = pd.merge(sleep, danger_t, on='Species', how='inner')
new_data = dataframe.dropna()
new_data

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
1,Africangiantpouchedrat,1.000,6.60,6.3,2.0,8.3,4.5,42.0,3,1,3
4,Asianelephant,2547.000,4603.00,2.1,1.8,3.9,69.0,624.0,3,5,4
5,Baboon,10.550,179.50,9.1,0.7,9.8,27.0,180.0,4,4,4
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,1
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,4
8,Cat,3.300,25.60,10.9,3.6,14.5,28.0,63.0,1,2,1
9,Chimpanzee,52.160,440.00,8.3,1.4,9.7,50.0,230.0,1,1,1
10,Chinchilla,0.425,6.40,11.0,1.5,12.5,7.0,112.0,5,4,4
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5
14,EasternAmericanmole,0.075,1.20,6.3,2.1,8.4,3.5,42.0,1,1,1
15,Echidna,3.000,25.00,8.6,0.0,8.6,50.0,28.0,2,2,2
16,Europeanhedgehog,0.785,3.50,6.6,4.1,10.7,6.0,42.0,2,2,2
17,Galago,0.200,5.00,9.5,1.2,10.7,10.4,120.0,2,2,2
21,Goat,27.660,115.00,3.3,0.5,3.8,20.0,148.0,5,5,5
22,Goldenhamster,0.120,1.00,11.0,3.4,14.4,3.9,16.0,3,1,2
24,Grayseal,85.000,325.00,4.7,1.5,6.2,41.0,310.0,1,3,1
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0,5,1,3
27,Guineapig,1.040,5.50,7.4,0.8,8.2,7.6,68.0,5,3,4
28,Horse,521.000,655.00,2.1,0.8,2.9,46.0,336.0,5,5,5
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1
33,Man,62.000,1320.00,6.1,1.9,8.0,100.0,267.0,1,1,1
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0,4,1,3
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0,4,1,3
38,NAmericanopossum,1.700,6.30,13.8,5.6,19.4,5.0,12.0,2,1,1
39,Nine-bandedarmadillo,3.500,10.80,14.3,3.1,17.4,6.5,120.0,2,1,1
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,2
42,Patasmonkey,10.000,115.00,10.0,0.9,10.9,20.2,170.0,4,4,4
43,Phanlanger,1.620,11.40,11.9,1.8,13.7,13.0,17.0,2,1,2
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4
45,Rabbit,2.500,12.10,7.5,0.9,8.4,18.0,31.0,5,5,5
47,Rat,0.280,1.90,10.6,2.6,13.2,4.7,21.0,3,1,3
48,Redfox,4.235,50.40,7.4,2.4,9.8,9.8,52.0,1,1,1
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,2
50,Rockhyrax(Heterob),0.750,12.30,5.7,0.9,6.6,7.0,225.0,2,2,2
51,Rockhyrax(Procaviahab),3.600,21.00,4.9,0.5,5.4,6.0,225.0,3,2,3
53,Sheep,55.500,175.00,3.2,0.6,3.8,20.0,151.0,5,5,5
56,Tenrec,0.900,2.60,11.0,2.3,13.3,4.5,60.0,2,1,2
57,Treehyrax,2.000,12.30,4.9,0.5,5.4,7.5,200.0,3,1,3
58,Treeshrew,0.104,2.50,13.2,2.6,15.8,2.3,46.0,3,2,2
59,Vervet,4.190,58.00,9.7,0.6,10.3,24.0,210.0,4,3,4
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,1

### Exercise 4
Investigate what ```how='inner'``` does and what other options exist.

The expression ```how='inner'``` performs an inner join between the two dataframes meaning that only species existing in both dataframes end up in the merged dataframe.

Other options are:
- ```how='left'```: includes all rows from the left dataframe, and matching rows from the right dataframe.

- ```how='right'```: includes all rows from the right dataframe, and matching rows from the left dataframe.

- ```how='outer'```: includes all rows from both data frames, with NaNs where there are no matches.

## 3. Indexing on a dataframe
From now on we work with our newly merged dataframe.
Indexing is quite useful to
- directly access a specific element in a dataframe.
- easily modify or assign values.
- filter.
- ...

We can access a single cell by indexing my its row and column

```
dataframe.iat[row_index,column_index]
```

### Exercise 5
Check what value lies in colum 4 row 58

In [ ]:
dataframe.iat[58,4]

np.float64(2.6)

We can also assign a new value to this cell using

```
dataframe.iat[row_index,column_index]=10
```

### Exercise 6
Overwrite the value in row 58 and column 4 with 10 and then change iz back to 4.9.

In [ ]:
dataframe.iat[58,4] = 10
dataframe.iat[58,4] = 4.9
dataframe

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4
...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3
58,Treeshrew,0.104,2.5,13.2,4.9,15.8,2.3,46.0,3,2,2
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1

We can also access multiple cells by


```
dataframe.iloc[min_row:max_row+1,min_col:max_col+1]
```

### Exercise 7
Look at the first 10 row and the last 3 columns of our dataframe.

In [ ]:
dataframe.iloc[0:10, 8:11]

   Predation  Exposure  Danger
0          3         5       3
1          3         1       3
2          1         1       1
3          5         2       3
4          3         5       4
5          4         4       4
6          1         1       1
7          4         5       4
8          1         2       1
9          1         1       1

**Important**
When you assign a (subset) of dataframe to a new one like above, no copy is made. This means that if you change values of the new frame, also the orginal frame will be changed. If you want a copy, you need to use the copy method.

We can also access colums by the column names.
### Exercise 8
Look at the *TotalSleep* of all species. and in a second step look at *TotalSleep* and *BrainWt* of the first sevel rows.

In [ ]:
dataframe[:]['TotalSleep']
dataframe[0:7][['TotalSleep', 'BrainWt']]

   TotalSleep  BrainWt
0         3.3   5712.0
1         8.3      6.6
2        12.5     44.5
3        16.5      5.7
4         3.9   4603.0
5         9.8    179.5
6        19.7      0.3

Selecting by row values

In [ ]:
dataframe[dataframe['Species']=='ArcticFox']

Sometimes it is also helpful to group. For example, if we are interested in the average *BrainWt* with respect to the danger the mammals are in, then grouping by *Danger* would yields the result:

In [ ]:
dataframe.groupby('Danger')['BrainWt'].mean()

Danger
1    159.434211
2     22.350000
3    577.233000
4    537.254000
5    340.811111
Name: BrainWt, dtype: float64

### Exercise 9
Look at the mean gestation grouped by sleep exposure. Is there some visible difference?

In [ ]:
dataframe.groupby('TotalSleep')['Gestation'].mean()

TotalSleep
2.6     150.000000
2.9     336.000000
3.1     365.000000
3.3     645.000000
3.8     149.500000
3.9     452.500000
5.4     212.500000
6.1            NaN
6.2     351.000000
6.6     225.000000
8.0     267.000000
8.2      68.000000
8.3      42.000000
8.4      62.666667
8.6      28.000000
9.1      21.500000
9.6     164.000000
9.7     230.000000
9.8     116.000000
10.3    210.000000
10.6     30.000000
10.7     81.000000
10.8    100.000000
10.9    170.000000
11.0     90.000000
11.2     45.000000
12.0    252.000000
12.5     78.333333
12.8     30.000000
13.0     63.000000
13.2     20.000000
13.3     60.000000
13.7     17.000000
13.8     28.000000
14.4     16.000000
14.5     63.000000
15.8     46.000000
16.5     25.000000
17.0    140.000000
17.4    120.000000
18.1           NaN
19.4     13.000000
19.7     35.000000
19.9     50.000000
Name: Gestation, dtype: float64

## 4. Sorting
Sorting is helpful because it allows you to organize data in a meaningful order, making it easier to identify patterns, trends, or outliers.

We can sort with respect to one or multiple columns as follows.



```
dataframe.sort_values(['col1','col2'])
```

### Exercise 9
Sort the dataframe with respect to time the mammals spend sleeping in total as well as dreaming.

In [ ]:
dataframe.sort_values(['TotalSleep', 'Dreaming'])

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
52,Roedeer,14.83,98.20,NaN,NaN,2.6,17.0,150.0,5,5,5
28,Horse,521.00,655.00,2.1,0.8,2.9,46.0,336.0,5,5,5
13,Donkey,187.10,419.00,NaN,NaN,3.1,40.0,365.0,5,5,5
0,Africanelephant,6654.00,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,3
21,Goat,27.66,115.00,3.3,0.5,3.8,20.0,148.0,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...
32,Littlebrownbat,0.01,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1
20,Giraffe,529.00,680.00,NaN,0.3,NaN,28.0,400.0,5,5,5
40,Okapi,250.00,490.00,NaN,1.0,NaN,23.6,440.0,5,5,5
30,Kangaroo,35.00,56.00,NaN,NaN,NaN,16.3,33.0,3,5,4
61,Yellow-belliedmarmot,4.05,17.00,NaN,NaN,NaN,13.0,38.0,3,1,1

## 5. Filtering
Filtering dataframes is helpful because it allows you to focus on specific subsets of data that meet certain criteria, simplifying analysis and making it easier to identify trends or anomalies. It also improves efficiency by reducing the volume of data processed, which speeds up computations and insights.

### Exercise 10
- Filter the data set such that only mammals remain that have a lifespan of more than 15 years.
- Filter the data set such that only mammals remain that have a lifespan of more than 15 years and have a danger index of 5.

In [ ]:
dataframe[dataframe['LifeSpan']>15]

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
0,Africanelephant,6654.000,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,3
4,Asianelephant,2547.000,4603.00,2.1,1.8,3.9,69.0,624.0,3,5,4
5,Baboon,10.550,179.50,9.1,0.7,9.8,27.0,180.0,4,4,4
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,1
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,4
8,Cat,3.300,25.60,10.9,3.6,14.5,28.0,63.0,1,2,1
9,Chimpanzee,52.160,440.00,8.3,1.4,9.7,50.0,230.0,1,1,1
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5
13,Donkey,187.100,419.00,NaN,NaN,3.1,40.0,365.0,5,5,5
15,Echidna,3.000,25.00,8.6,0.0,8.6,50.0,28.0,2,2,2
18,Genet,1.410,17.50,4.8,1.3,6.1,34.0,NaN,1,2,1
20,Giraffe,529.000,680.00,NaN,0.3,NaN,28.0,400.0,5,5,5
21,Goat,27.660,115.00,3.3,0.5,3.8,20.0,148.0,5,5,5
23,Gorilla,207.000,406.00,NaN,NaN,12.0,39.3,252.0,1,4,1
24,Grayseal,85.000,325.00,4.7,1.5,6.2,41.0,310.0,1,3,1
25,Graywolf,36.330,119.50,NaN,NaN,13.0,16.2,63.0,1,1,1
28,Horse,521.000,655.00,2.1,0.8,2.9,46.0,336.0,5,5,5
29,Jaguar,100.000,157.00,NaN,NaN,10.8,22.4,100.0,1,1,1
30,Kangaroo,35.000,56.00,NaN,NaN,NaN,16.3,33.0,3,5,4
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1
33,Man,62.000,1320.00,6.1,1.9,8.0,100.0,267.0,1,1,1
40,Okapi,250.000,490.00,NaN,1.0,NaN,23.6,440.0,5,5,5
42,Patasmonkey,10.000,115.00,10.0,0.9,10.9,20.2,170.0,4,4,4
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4
45,Rabbit,2.500,12.10,7.5,0.9,8.4,18.0,31.0,5,5,5
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,2
52,Roedeer,14.830,98.20,NaN,NaN,2.6,17.0,150.0,5,5,5
53,Sheep,55.500,175.00,3.2,0.6,3.8,20.0,151.0,5,5,5
59,Vervet,4.190,58.00,9.7,0.6,10.3,24.0,210.0,4,3,4

In [ ]:
dataframe[(dataframe['LifeSpan'] > 15) & (dataframe['Danger'] == 5)]

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
11,Cow,465.00,423.0,3.2,0.7,3.9,30.0,281.0,5,5,5
13,Donkey,187.10,419.0,NaN,NaN,3.1,40.0,365.0,5,5,5
20,Giraffe,529.00,680.0,NaN,0.3,NaN,28.0,400.0,5,5,5
21,Goat,27.66,115.0,3.3,0.5,3.8,20.0,148.0,5,5,5
28,Horse,521.00,655.0,2.1,0.8,2.9,46.0,336.0,5,5,5
40,Okapi,250.00,490.0,NaN,1.0,NaN,23.6,440.0,5,5,5
45,Rabbit,2.50,12.1,7.5,0.9,8.4,18.0,31.0,5,5,5
52,Roedeer,14.83,98.2,NaN,NaN,2.6,17.0,150.0,5,5,5
53,Sheep,55.50,175.0,3.2,0.6,3.8,20.0,151.0,5,5,5

## 6. Missing or bad data

Datasets, before they are "cleaned", may contain missing or wrongly formated values. There are DataFrame methods to deal with this:

- DataFrame.dropna([axis, how, thresh, …])	Remove missing values.
- DataFrame.fillna([value, method, axis, …])	Fill NA/NaN values using the specified method
- DataFrame.replace([to_replace, value, …])	Replace values given in to_replace with value.
- DataFrame.interpolate([method, axis, limit, …])	Interpolate values according to different methods.

Retrieving and cleaning data is often the most time consuming part in a data science project.

## 7. Exporting dataframes (I/O)

DataFrame has several export methods. (html, hdf5, ascii, excel etc). Let's save file in csv format.

In [ ]:
dataframe.to_csv('merged.csv')
files.download('merged.csv')

Can you find it?

What happens with our files when we close our colab session?

## 8. Metadata


Metadata is data about the data, e.g. when was it collected, under which conditions, calibration etc.
Metadata is normally not part of the statistical data analysis, however, needed for understanding and reproducibilty.

DataFrame is not really made for storing metadata (should be done separately), but one can add new attributes to a dataframe:

In [ ]:
import pandas as pd
metadata = {
    'Location': "Gaul",
    'Authors': ['Asterix', "Obelix", 'Idefix']
}
metadata = pd.DataFrame(metadata)
metadata

  Location  Authors
0     Gaul  Asterix
1     Gaul   Obelix
2     Gaul   Idefix

Data repositories often use so-called Data Cards for metadata. See for example: https://www.kaggle.com/datasets/uciml/iris

## 9. Two more Exercises

### Exercise 11
Download the iris.csv from Github. Read in the iris dataset into a dataframe. Set the values in column 1 in row 39, 49 and 100 to NaN (use the nan method from the numpy package). Then replacethe NaN values to the average value of the respective column. Depending on how you do it, this may be about 10 lines of Python code.

In [ ]:
import pandas as pd
import numpy as np

url = 'https://github.com/KGzB/CAS-Applied-Data-Science/blob/master/Module-1/iris.csv?raw=true'
iris = pd.read_csv(url, sep=',', names=['slength', 'swidth', 'plength', 'pwidth', 'species'])

# set values to NaN
iris.iloc[[38,48,99],0]= np.nan

# Calculate mean
mean_value = iris['slength'].mean()

# Replace NaN values in column1 with the mean value
iris['slength'].fillna(mean_value, inplace=True)

# Check
iris.iloc[[38,48,99],0]

/tmp/ipython-input-2559998333.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris['slength'].fillna(mean_value, inplace=True)

38    5.857823
48    5.857823
99    5.857823
Name: slength, dtype: float64

### Exercise 12
This exercise presents a real-world scenario based on data collected from a student survey for a university course on statistics for economics and social sciences. To practice data handling in Python, you'll work with this dataset to prepare it for analysis.

The survey gathered responses on five variables:

* Mobile OS: The operating system of the student's mobile phone.
* Screen time: Daily screen time in minutes.
* Shopping preference: The student's preferred method of shopping (online or in-store).
* Favorite subject: Their favorite subject during high school.
* Weekly sports time: The number of hours spent on sports each week.

The raw datasets are available for download on ILIAS. Your task is to merge and clean the data to make it usable. This includes: Identify and handle any data points that are clearly incorrect or nonsensical. The "favorite subject" variable is particularly messy due to free-form text input. You'll need to
develop a strategy to categorize these answers consistently. There isn't a single correct approach, but this task demonstrates how crucial careful study design is to avoid common data cleaning issues.

In [ ]:
import pandas as pd


Data = pd.read_csv('Stat2023.csv', sep=",", index_col = 0)
Data_1 = pd.read_csv('Stat2024.csv', sep=",", index_col = 0)

In [ ]:
Data['year'] = 2023
Data_1['year'] = 2024
combined_df = pd.concat([Data, Data_1], ignore_index=True)
combined_df

,Handybetriebssystem,Bildschimzeit_in_Minuten,Shoppingverhalten,Lieblingsfach,Sport_in_Stunden,Kleidergroesse,year
0,iOS,180.0,online,Religion,1.0,M,2023
1,iOS,330.0,offline,Wirtschaft & Recht,7.5,M,2023
2,iOS,240.0,offline,Physical Education,14.0,M,2023
3,Android,120.0,offline,Philosophie,3.0,M,2023
4,iOS,240.0,offline,BG,10.0,M,2023
...,...,...,...,...,...,...,...
566,iOS,240.0,offline,Wirtschaft und Recht,5.0,S,2024
567,Android,100.0,online,Mathe,2.0,S,2024
568,iOS,180.0,offline,Deutsch,5.0,S,2024
569,iOS,150.0,offline,Biologie,5.0,S,2024
570,iOS,240.0,offline,Kunst,3.0,S,2024

In [ ]:
print(sleep['Species'].dtype)
print(danger_t['Species'].dtype)

object
object

In [ ]:
Data['year'] = 2023
Data_1['year'] = 2024
combined_df = pd.concat([Data, Data_1], ignore_index=True)
combined_df

,Handybetriebssystem,Bildschimzeit_in_Minuten,Shoppingverhalten,Lieblingsfach,Sport_in_Stunden,Kleidergroesse,year
0,iOS,180.0,online,Religion,1.0,M,2023
1,iOS,330.0,offline,Wirtschaft & Recht,7.5,M,2023
2,iOS,240.0,offline,Physical Education,14.0,M,2023
3,Android,120.0,offline,Philosophie,3.0,M,2023
4,iOS,240.0,offline,BG,10.0,M,2023
...,...,...,...,...,...,...,...
566,iOS,240.0,offline,Wirtschaft und Recht,5.0,S,2024
567,Android,100.0,online,Mathe,2.0,S,2024
568,iOS,180.0,offline,Deutsch,5.0,S,2024
569,iOS,150.0,offline,Biologie,5.0,S,2024
570,iOS,240.0,offline,Kunst,3.0,S,2024

In [ ]:
#Filtering the data based on columns
combined_df[(combined_df['Lieblingsfach'] == 'Physical Education') & (combined_df['year'] == 2023)]
combined_df[(combined_df['Lieblingsfach'] == 'Physical Education') & (combined_df['Handybetriebssystem'] == 'iOS')]

,Handybetriebssystem,Bildschimzeit_in_Minuten,Shoppingverhalten,Lieblingsfach,Sport_in_Stunden,Kleidergroesse,year
2,iOS,240.0,offline,Physical Education,14.0,M,2023